name: Main workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        make install
        make lint
        make test
      env:
        CI: true
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: 7184eb8c17819075355f0697c79b5e3bbff843a36cbe0b25cf70424d3a264d37
      with:
        coverageCommand: make test-coverage
        debug: true
